package com.cuzz.rookiecrates.model;

import java.util.ArrayList;
import java.util.List;

public class DCrateLootExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public DCrateLootExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andRarityIsNull() {
            addCriterion("rarity is null");
            return (Criteria) this;
        }

        public Criteria andRarityIsNotNull() {
            addCriterion("rarity is not null");
            return (Criteria) this;
        }

        public Criteria andRarityEqualTo(String value) {
            addCriterion("rarity =", value, "rarity");
            return (Criteria) this;
        }

        public Criteria andRarityNotEqualTo(String value) {
            addCriterion("rarity <>", value, "rarity");
            return (Criteria) this;
        }

        public Criteria andRarityGreaterThan(String value) {
            addCriterion("rarity >", value, "rarity");
            return (Criteria) this;
        }

        public Criteria andRarityGreaterThanOrEqualTo(String value) {
            addCriterion("rarity >=", value, "rarity");
            return (Criteria) this;
        }

        public Criteria andRarityLessThan(String value) {
            addCriterion("rarity <", value, "rarity");
            return (Criteria) this;
        }

        public Criteria andRarityLessThanOrEqualTo(String value) {
            addCriterion("rarity <=", value, "rarity");
            return (Criteria) this;
        }

        public Criteria andRarityLike(String value) {
            addCriterion("rarity like", value, "rarity");
            return (Criteria) this;
        }

        public Criteria andRarityNotLike(String value) {
            addCriterion("rarity not like", value, "rarity");
            return (Criteria) this;
        }

        public Criteria andRarityIn(List<String> values) {
            addCriterion("rarity in", values, "rarity");
            return (Criteria) this;
        }

        public Criteria andRarityNotIn(List<String> values) {
            addCriterion("rarity not in", values, "rarity");
            return (Criteria) this;
        }

        public Criteria andRarityBetween(String value1, String value2) {
            addCriterion("rarity between", value1, value2, "rarity");
            return (Criteria) this;
        }

        public Criteria andRarityNotBetween(String value1, String value2) {
            addCriterion("rarity not between", value1, value2, "rarity");
            return (Criteria) this;
        }

        public Criteria andCrateIdIsNull() {
            addCriterion("crate_id is null");
            return (Criteria) this;
        }

        public Criteria andCrateIdIsNotNull() {
            addCriterion("crate_id is not null");
            return (Criteria) this;
        }

        public Criteria andCrateIdEqualTo(String value) {
            addCriterion("crate_id =", value, "crateId");
            return (Criteria) this;
        }

        public Criteria andCrateIdNotEqualTo(String value) {
            addCriterion("crate_id <>", value, "crateId");
            return (Criteria) this;
        }

        public Criteria andCrateIdGreaterThan(String value) {
            addCriterion("crate_id >", value, "crateId");
            return (Criteria) this;
        }

        public Criteria andCrateIdGreaterThanOrEqualTo(String value) {
            addCriterion("crate_id >=", value, "crateId");
            return (Criteria) this;
        }

        public Criteria andCrateIdLessThan(String value) {
            addCriterion("crate_id <", value, "crateId");
            return (Criteria) this;
        }

        public Criteria andCrateIdLessThanOrEqualTo(String value) {
            addCriterion("crate_id <=", value, "crateId");
            return (Criteria) this;
        }

        public Criteria andCrateIdLike(String value) {
            addCriterion("crate_id like", value, "crateId");
            return (Criteria) this;
        }

        public Criteria andCrateIdNotLike(String value) {
            addCriterion("crate_id not like", value, "crateId");
            return (Criteria) this;
        }

        public Criteria andCrateIdIn(List<String> values) {
            addCriterion("crate_id in", values, "crateId");
            return (Criteria) this;
        }

        public Criteria andCrateIdNotIn(List<String> values) {
            addCriterion("crate_id not in", values, "crateId");
            return (Criteria) this;
        }

        public Criteria andCrateIdBetween(String value1, String value2) {
            addCriterion("crate_id between", value1, value2, "crateId");
            return (Criteria) this;
        }

        public Criteria andCrateIdNotBetween(String value1, String value2) {
            addCriterion("crate_id not between", value1, value2, "crateId");
            return (Criteria) this;
        }

        public Criteria andLootItemstackBase64IsNull() {
            addCriterion("loot_itemstack_base64 is null");
            return (Criteria) this;
        }

        public Criteria andLootItemstackBase64IsNotNull() {
            addCriterion("loot_itemstack_base64 is not null");
            return (Criteria) this;
        }

        public Criteria andLootItemstackBase64EqualTo(String value) {
            addCriterion("loot_itemstack_base64 =", value, "lootItemstackBase64");
            return (Criteria) this;
        }

        public Criteria andLootItemstackBase64NotEqualTo(String value) {
            addCriterion("loot_itemstack_base64 <>", value, "lootItemstackBase64");
            return (Criteria) this;
        }

        public Criteria andLootItemstackBase64GreaterThan(String value) {
            addCriterion("loot_itemstack_base64 >", value, "lootItemstackBase64");
            return (Criteria) this;
        }

        public Criteria andLootItemstackBase64GreaterThanOrEqualTo(String value) {
            addCriterion("loot_itemstack_base64 >=", value, "lootItemstackBase64");
            return (Criteria) this;
        }

        public Criteria andLootItemstackBase64LessThan(String value) {
            addCriterion("loot_itemstack_base64 <", value, "lootItemstackBase64");
            return (Criteria) this;
        }

        public Criteria andLootItemstackBase64LessThanOrEqualTo(String value) {
            addCriterion("loot_itemstack_base64 <=", value, "lootItemstackBase64");
            return (Criteria) this;
        }

        public Criteria andLootItemstackBase64Like(String value) {
            addCriterion("loot_itemstack_base64 like", value, "lootItemstackBase64");
            return (Criteria) this;
        }

        public Criteria andLootItemstackBase64NotLike(String value) {
            addCriterion("loot_itemstack_base64 not like", value, "lootItemstackBase64");
            return (Criteria) this;
        }

        public Criteria andLootItemstackBase64In(List<String> values) {
            addCriterion("loot_itemstack_base64 in", values, "lootItemstackBase64");
            return (Criteria) this;
        }

        public Criteria andLootItemstackBase64NotIn(List<String> values) {
            addCriterion("loot_itemstack_base64 not in", values, "lootItemstackBase64");
            return (Criteria) this;
        }

        public Criteria andLootItemstackBase64Between(String value1, String value2) {
            addCriterion("loot_itemstack_base64 between", value1, value2, "lootItemstackBase64");
            return (Criteria) this;
        }

        public Criteria andLootItemstackBase64NotBetween(String value1, String value2) {
            addCriterion("loot_itemstack_base64 not between", value1, value2, "lootItemstackBase64");
            return (Criteria) this;
        }

        public Criteria andLoresIsNull() {
            addCriterion("lores is null");
            return (Criteria) this;
        }

        public Criteria andLoresIsNotNull() {
            addCriterion("lores is not null");
            return (Criteria) this;
        }

        public Criteria andLoresEqualTo(String value) {
            addCriterion("lores =", value, "lores");
            return (Criteria) this;
        }

        public Criteria andLoresNotEqualTo(String value) {
            addCriterion("lores <>", value, "lores");
            return (Criteria) this;
        }

        public Criteria andLoresGreaterThan(String value) {
            addCriterion("lores >", value, "lores");
            return (Criteria) this;
        }

        public Criteria andLoresGreaterThanOrEqualTo(String value) {
            addCriterion("lores >=", value, "lores");
            return (Criteria) this;
        }

        public Criteria andLoresLessThan(String value) {
            addCriterion("lores <", value, "lores");
            return (Criteria) this;
        }

        public Criteria andLoresLessThanOrEqualTo(String value) {
            addCriterion("lores <=", value, "lores");
            return (Criteria) this;
        }

        public Criteria andLoresLike(String value) {
            addCriterion("lores like", value, "lores");
            return (Criteria) this;
        }

        public Criteria andLoresNotLike(String value) {
            addCriterion("lores not like", value, "lores");
            return (Criteria) this;
        }

        public Criteria andLoresIn(List<String> values) {
            addCriterion("lores in", values, "lores");
            return (Criteria) this;
        }

        public Criteria andLoresNotIn(List<String> values) {
            addCriterion("lores not in", values, "lores");
            return (Criteria) this;
        }

        public Criteria andLoresBetween(String value1, String value2) {
            addCriterion("lores between", value1, value2, "lores");
            return (Criteria) this;
        }

        public Criteria andLoresNotBetween(String value1, String value2) {
            addCriterion("lores not between", value1, value2, "lores");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Double value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Double value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Double value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Double value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Double value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Double value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Double> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Double> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Double value1, Double value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Double value1, Double value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(Integer value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(Integer value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(Integer value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(Integer value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(Integer value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<Integer> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<Integer> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(Integer value1, Integer value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated do_not_delete_during_merge Wed May 07 18:21:10 CST 2025
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rookie_crate_loot
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}