package com.cuzz.rookiecrates.model;

public class DCrateLoot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookie_crate_loot.id
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookie_crate_loot.name
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookie_crate_loot.rarity
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    private String rarity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookie_crate_loot.crate_id
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    private String crateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookie_crate_loot.loot_itemstack_base64
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    private String lootItemstackBase64;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookie_crate_loot.lores
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    private String lores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookie_crate_loot.description
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookie_crate_loot.weight
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookie_crate_loot.amount
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    private Integer amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookie_crate_loot.id
     *
     * @return the value of rookie_crate_loot.id
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookie_crate_loot.id
     *
     * @param id the value for rookie_crate_loot.id
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookie_crate_loot.name
     *
     * @return the value of rookie_crate_loot.name
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookie_crate_loot.name
     *
     * @param name the value for rookie_crate_loot.name
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookie_crate_loot.rarity
     *
     * @return the value of rookie_crate_loot.rarity
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public String getRarity() {
        return rarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookie_crate_loot.rarity
     *
     * @param rarity the value for rookie_crate_loot.rarity
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public void setRarity(String rarity) {
        this.rarity = rarity == null ? null : rarity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookie_crate_loot.crate_id
     *
     * @return the value of rookie_crate_loot.crate_id
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public String getCrateId() {
        return crateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookie_crate_loot.crate_id
     *
     * @param crateId the value for rookie_crate_loot.crate_id
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public void setCrateId(String crateId) {
        this.crateId = crateId == null ? null : crateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookie_crate_loot.loot_itemstack_base64
     *
     * @return the value of rookie_crate_loot.loot_itemstack_base64
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public String getLootItemstackBase64() {
        return lootItemstackBase64;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookie_crate_loot.loot_itemstack_base64
     *
     * @param lootItemstackBase64 the value for rookie_crate_loot.loot_itemstack_base64
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public void setLootItemstackBase64(String lootItemstackBase64) {
        this.lootItemstackBase64 = lootItemstackBase64 == null ? null : lootItemstackBase64.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookie_crate_loot.lores
     *
     * @return the value of rookie_crate_loot.lores
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public String getLores() {
        return lores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookie_crate_loot.lores
     *
     * @param lores the value for rookie_crate_loot.lores
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public void setLores(String lores) {
        this.lores = lores == null ? null : lores.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookie_crate_loot.description
     *
     * @return the value of rookie_crate_loot.description
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookie_crate_loot.description
     *
     * @param description the value for rookie_crate_loot.description
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookie_crate_loot.weight
     *
     * @return the value of rookie_crate_loot.weight
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookie_crate_loot.weight
     *
     * @param weight the value for rookie_crate_loot.weight
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookie_crate_loot.amount
     *
     * @return the value of rookie_crate_loot.amount
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookie_crate_loot.amount
     *
     * @param amount the value for rookie_crate_loot.amount
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}