package com.cuzz.rookiecrates.model;

public class DCrate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookie_crate.id
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookie_crate.name
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookie_crate.id
     *
     * @return the value of rookie_crate.id
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookie_crate.id
     *
     * @param id the value for rookie_crate.id
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookie_crate.name
     *
     * @return the value of rookie_crate.name
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookie_crate.name
     *
     * @param name the value for rookie_crate.name
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}