package com.cuzz.rookiecrates.mapper;

import com.cuzz.rookiecrates.model.DCrate;
import com.cuzz.rookiecrates.model.DCrateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DCrateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    int countByExample(DCrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    int deleteByExample(DCrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    int insert(DCrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    int insertSelective(DCrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    List<DCrate> selectByExample(DCrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    DCrate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    int updateByExampleSelective(@Param("record") DCrate record, @Param("example") DCrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    int updateByExample(@Param("record") DCrate record, @Param("example") DCrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    int updateByPrimaryKeySelective(DCrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookie_crate
     *
     * @mbggenerated Wed May 07 18:21:10 CST 2025
     */
    int updateByPrimaryKey(DCrate record);
}